# Aliasy lokalnej bazy testowej Menadżera Serwisu.
# Klient MS może automatycznie dopisać nazwę pliku BazaMS.fdb.
BAZAMS_TEST = /data/BAZAMS_TEST.FDB
BAZAMS_TEST\BazaMS.fdb = /data/BAZAMS_TEST.FDB
BAZAMS_TEST/BazaMS.fdb = /data/BAZAMS_TEST.FDB
